SandwaveIo\Office365\Entity\CloudTenant:
  exclusion_policy: ALL

  xml_root_name: CloudTenant_V2

  properties:

    tenantId:
      expose: true
      type: string
      serialized_name: TenantId

    name:
      expose: true
      type: string
      serialized_name: TenantName

    firstname:
      expose: true
      type: string
      serialized_name: FirstName

    lastname:
      expose: true
      type: string
      serialized_name: LastName

    email:
      expose: true
      type: string
      serialized_name: EmailAddress

