SandwaveIo\Office365\Entity\CloudLicense:

  exclusion_policy: ALL

  xml_root_name: NewCloudLicenseOrderRequest_V2

  properties:

    header:
      expose: true
      type: SandwaveIo\Office365\Entity\Header\PartnerReferenceHeader
      serialized_name: Header

    tenant:
      expose: true
      type: SandwaveIo\Office365\Entity\CloudTenant
      serialized_name: CloudTenant_V2

    contact:
      expose: true
      type: SandwaveIo\Office365\Entity\AgreementContact
      serialized_name: CustomerAgreementContact_V1
