SandwaveIo\Office365\Entity\Customer:
  exclusion_policy: ALL

  xml_root_name: NewCustomerRequest_V3

  properties:

    header:
      expose: true
      type: SandwaveIo\Office365\Entity\Header\CustomerHeader
      serialized_name: Header

    name:
      expose: true
      type: string
      serialized_name: Name
