Office365\Entity\Customer:
  exclusion_policy: ALL

  properties:

    header:
      expose: true
      type: Office365\Entity\Header\CustomerHeader
      serialized_name: Header

    name:
      expose: true
      type: string
      serialized_name: Name
