customer:
  create:
    method: post
    url: '/api/queued'

  modify:
    method: post
    url: '/api/queued'

  has_domain_ownership:
    method: post
    url: '/api/realtime'

tenant:
  exists:
    method: post
    url: '/api/realtime'

  fetch_tenant:
    method: post
    url: '/api/realtime'

order:
  license_create:
    method: post
    url: '/api/queued'

  modify:
    method: post
    url: '/api/queued'

contact:
  create:
    method: post
    url: '/api/queued'

addon:
  create:
    method: post
    url: '/api/queued'

terminate:
  order:
    method: post
    url: '/api/queued'
